import bcrypt from "bcrypt";

export const FakeData = {
  User: [
    {
      name: "Mentor 1",
      email: "mentor@gmail.com",
      number: "1234567890",
      token: "ya29.A0AVA9y1undHrBmFdogiI1zM7sxp2oUjrghyqHAvZuxetrefoKEJg5BGKDoBhF9HoAcd--fedaU6yCMrCg9fA912z-qJvVXfTQ5qrAY0iq8bD4Fadx1hVfHBr8uVA6XzbzYwvjbTKtcQO0da7zGEEVN4syET0hvgYUNnWUtBVEFTQVRBU0ZRRTY1ZHI4eEVQQkJGekROUllpdmtwNTlsVzN4QQ0164",
      dob: "2022-01-02",
      picture: "https://lh3.googleusercontent.com/a-/AFdZucoL4jmIfrGWVP7-mfSoNbqHMsTlfrRIGUtLThr3cQ=s96-c",
      sector: "Schooling",
      stream: "LKG",
      role: "mentor",
      slots: []
    },
    {
      name: "Mentor 2",
      email: "mentor2@gmail.com",
      number: "1234567890",
      token: "ya29.A0AVA9y1undHrBmFdogiI1zM7sxp2oUjrghyqHAvZuxetrefoKEJg5BGKDoBhF9HoAcd--fedaU6yCMrCg9fA912z-qJvVXfTQ5qrAY0iq8bD4Fadx1hVfHBr8uVA6XzbzYwvjbTKtcQO0da7zGEEVN4syET0hvgYUNnWUtBVEFTQVRBU0ZRRTY1ZHI4eEVQQkJGekROUllpdmtwNTlsVzN4QQ0164",
      dob: "2022-01-02",
      picture: "https://lh3.googleusercontent.com/a-/AFdZucoL4jmIfrGWVP7-mfSoNbqHMsTlfrRIGUtLThr3cQ=s96-c",
      sector: "Schooling",
      stream: "UKG",
      role: "mentor"
    },
    {
      name: "Mentor 3",
      email: "mentor3@gmail.com",
      number: "1234567890",
      token: "ya29.A0AVA9y1undHrBmFdogiI1zM7sxp2oUjrghyqHAvZuxetrefoKEJg5BGKDoBhF9HoAcd--fedaU6yCMrCg9fA912z-qJvVXfTQ5qrAY0iq8bD4Fadx1hVfHBr8uVA6XzbzYwvjbTKtcQO0da7zGEEVN4syET0hvgYUNnWUtBVEFTQVRBU0ZRRTY1ZHI4eEVQQkJGekROUllpdmtwNTlsVzN4QQ0164",
      dob: "2022-01-02",
      picture: "https://lh3.googleusercontent.com/a-/AFdZucoL4jmIfrGWVP7-mfSoNbqHMsTlfrRIGUtLThr3cQ=s96-c",
      sector: "Junior College",
      stream: "11th",
      subStream: "Science",
      role: "mentor"
    },
    {
      name: "Mentor 4",
      email: "mentor4@gmail.com",
      number: "1234567890",
      token: "ya29.A0AVA9y1undHrBmFdogiI1zM7sxp2oUjrghyqHAvZuxetrefoKEJg5BGKDoBhF9HoAcd--fedaU6yCMrCg9fA912z-qJvVXfTQ5qrAY0iq8bD4Fadx1hVfHBr8uVA6XzbzYwvjbTKtcQO0da7zGEEVN4syET0hvgYUNnWUtBVEFTQVRBU0ZRRTY1ZHI4eEVQQkJGekROUllpdmtwNTlsVzN4QQ0164",
      dob: "2022-01-02",
      picture: "https://lh3.googleusercontent.com/a-/AFdZucoL4jmIfrGWVP7-mfSoNbqHMsTlfrRIGUtLThr3cQ=s96-c",
      sector: "Junior College",
      stream: "12th",
      subStream: "Commerce",
      role: "mentor"
    },
    {
      name: "Mentor 5",
      email: "mentor5@gmail.com",
      number: "1234567890",
      token: "ya29.A0AVA9y1undHrBmFdogiI1zM7sxp2oUjrghyqHAvZuxetrefoKEJg5BGKDoBhF9HoAcd--fedaU6yCMrCg9fA912z-qJvVXfTQ5qrAY0iq8bD4Fadx1hVfHBr8uVA6XzbzYwvjbTKtcQO0da7zGEEVN4syET0hvgYUNnWUtBVEFTQVRBU0ZRRTY1ZHI4eEVQQkJGekROUllpdmtwNTlsVzN4QQ0164",
      dob: "2022-01-02",
      picture: "https://lh3.googleusercontent.com/a-/AFdZucoL4jmIfrGWVP7-mfSoNbqHMsTlfrRIGUtLThr3cQ=s96-c",
      sector: "Schooling",
      stream: "LKG",
      role: "mentor"
    },
    {
      name: "Mentor 6",
      email: "mentor6@gmail.com",
      number: "1234567890",
      token: "ya29.A0AVA9y1undHrBmFdogiI1zM7sxp2oUjrghyqHAvZuxetrefoKEJg5BGKDoBhF9HoAcd--fedaU6yCMrCg9fA912z-qJvVXfTQ5qrAY0iq8bD4Fadx1hVfHBr8uVA6XzbzYwvjbTKtcQO0da7zGEEVN4syET0hvgYUNnWUtBVEFTQVRBU0ZRRTY1ZHI4eEVQQkJGekROUllpdmtwNTlsVzN4QQ0164",
      dob: "2022-01-02",
      picture: "https://lh3.googleusercontent.com/a-/AFdZucoL4jmIfrGWVP7-mfSoNbqHMsTlfrRIGUtLThr3cQ=s96-c",
      sector: "Schooling",
      stream: "LKG",
      role: "mentor"
    },
    {
      name: "Mentor 7",
      email: "mentor7@gmail.com",
      number: "1234567890",
      token: "ya29.A0AVA9y1undHrBmFdogiI1zM7sxp2oUjrghyqHAvZuxetrefoKEJg5BGKDoBhF9HoAcd--fedaU6yCMrCg9fA912z-qJvVXfTQ5qrAY0iq8bD4Fadx1hVfHBr8uVA6XzbzYwvjbTKtcQO0da7zGEEVN4syET0hvgYUNnWUtBVEFTQVRBU0ZRRTY1ZHI4eEVQQkJGekROUllpdmtwNTlsVzN4QQ0164",
      dob: "2022-01-02",
      picture: "https://lh3.googleusercontent.com/a-/AFdZucoL4jmIfrGWVP7-mfSoNbqHMsTlfrRIGUtLThr3cQ=s96-c",
      sector: "Schooling",
      stream: "LKG",
      role: "mentor"
    },
    {
      name: "Mentor 8",
      email: "mentor8@gmail.com",
      number: "1234567890",
      token: "ya29.A0AVA9y1undHrBmFdogiI1zM7sxp2oUjrghyqHAvZuxetrefoKEJg5BGKDoBhF9HoAcd--fedaU6yCMrCg9fA912z-qJvVXfTQ5qrAY0iq8bD4Fadx1hVfHBr8uVA6XzbzYwvjbTKtcQO0da7zGEEVN4syET0hvgYUNnWUtBVEFTQVRBU0ZRRTY1ZHI4eEVQQkJGekROUllpdmtwNTlsVzN4QQ0164",
      dob: "2022-01-02",
      picture: "https://lh3.googleusercontent.com/a-/AFdZucoL4jmIfrGWVP7-mfSoNbqHMsTlfrRIGUtLThr3cQ=s96-c",
      sector: "Schooling",
      stream: "LKG",
      role: "mentor"
    },
    {
      name: "Mentor 9",
      email: "mentor9@gmail.com",
      number: "1234567890",
      token: "ya29.A0AVA9y1undHrBmFdogiI1zM7sxp2oUjrghyqHAvZuxetrefoKEJg5BGKDoBhF9HoAcd--fedaU6yCMrCg9fA912z-qJvVXfTQ5qrAY0iq8bD4Fadx1hVfHBr8uVA6XzbzYwvjbTKtcQO0da7zGEEVN4syET0hvgYUNnWUtBVEFTQVRBU0ZRRTY1ZHI4eEVQQkJGekROUllpdmtwNTlsVzN4QQ0164",
      dob: "2022-01-02",
      picture: "https://lh3.googleusercontent.com/a-/AFdZucoL4jmIfrGWVP7-mfSoNbqHMsTlfrRIGUtLThr3cQ=s96-c",
      sector: "Schooling",
      stream: "LKG",
      role: "mentor"
    },
    {
      name: "Mentor 10",
      email: "mentor10@gmail.com",
      number: "1234567890",
      token: "ya29.A0AVA9y1undHrBmFdogiI1zM7sxp2oUjrghyqHAvZuxetrefoKEJg5BGKDoBhF9HoAcd--fedaU6yCMrCg9fA912z-qJvVXfTQ5qrAY0iq8bD4Fadx1hVfHBr8uVA6XzbzYwvjbTKtcQO0da7zGEEVN4syET0hvgYUNnWUtBVEFTQVRBU0ZRRTY1ZHI4eEVQQkJGekROUllpdmtwNTlsVzN4QQ0164",
      dob: "2022-01-02",
      picture: "https://lh3.googleusercontent.com/a-/AFdZucoL4jmIfrGWVP7-mfSoNbqHMsTlfrRIGUtLThr3cQ=s96-c",
      sector: "Schooling",
      stream: "LKG",
      role: "mentor"
    },
  ],
  DropdownData: [
    {
      name: "Schooling",
      streams: [
        { name: "Nursery" },
        { name: "LKG" },
        { name: "UKG" },
        { name: "1st" },
        { name: "2nd" },
        { name: "3rd" },
        { name: "4th" },
        { name: "5th" },
        { name: "6th" },
        { name: "7th" },
        { name: "8th" },
        { name: "9th" },
        { name: "10th" },
      ],
    },
    {
      name: "Junior College",
      streams: [
        {
          name: "11th",
          subStreams: [
            { name: "Science" },
            { name: "Commerce" },
            { name: "Arts" },
          ],
        },
        {
          name: "12th",
          subStreams: [
            { name: "Science" },
            { name: "Commerce" },
            { name: "Arts" },
          ],
        },
      ],
    },
    {
      name: "Diploma",
      streams: [
        { name: "Fashion Technology" },
        {
          name: "Engineering Sciences",
          subStreams: [
            { name: "CS & IT" },
            { name: "Civil" },
            { name: "Mechanical" },
            { name: "Electrical" },
            { name: "Textile" },
            { name: "Automobile" },
            { name: "Chemical" },
            { name: "Aeronautical" },
            { name: "Petroleum" },
            { name: "Mining" },
            { name: "Instrumentation" },
            { name: "Metallurgy" },
            { name: "Electronics" },
            { name: "ENTC" },
          ],
        },
        { name: "Ceramic  Technology" },
        { name: "Plastic  Technology" },
        { name: "Commercial Practice" },
        {
          name: "Management",
          subStreams: [
            { name: "Hotel" },
            { name: "Event" },
            { name: "Business" },
            { name: "Digital" },
          ],
        },
        { name: "Agriculture" },
        { name: "Cyber Security and Ethical Hacking" },
        { name: "Cosmetology" },
        { name: "Art Teacher" },
        { name: "Stenography" },
        { name: "Journalism" },
        { name: "D.ED" },
        { name: "Photography" },
        { name: "Psychology" },
        { name: "Designing" },
        { name: "Accounting" },
        {
          name: "Paramedical",
          subStreams: [
            { name: "Hospital Assistance" },
            { name: "Rural HealthCare" },
            { name: "Lab Technicians" },
            { name: "Paramedical Nursing" },
            { name: "Physiotherepy" },
            { name: "X-Ray Technology" },
            { name: "ECG Technology" },
            { name: "Radiology" },
            { name: "Dental Mechanics" },
            { name: "Pharmacy" },
          ],
        },
        {
          name: "ITI",
          subStreams: [
            { name: "Electrician" },
            { name: "Book Binder" },
            { name: "Carpenter" },
            { name: "Cutting Sewing" },
            { name: "Mechanics" },
            { name: "Plumber" },
            { name: "Welder" },
            { name: "Factory Operators" },
            { name: "Mason and Construction worker" },
            { name: "Insurance Agent" },
            { name: "GoldSmith" },
            { name: "DTP" },
            { name: "Helper in all fields" },
          ],
        },
      ],
    },
    {
      name: "Sports Careers",
      streams: [
        { name: "Athletic Director" },
        { name: "Athletic Sports" },
        { name: "Athletic Trainer" },
        { name: "Athletic Couch" },
        { name: "Nutritionist" },
        { name: "Personal Trainer" },
        { name: "Refree" },
        { name: "Sports Anchor" },
        { name: "Sports Writer" },
        { name: "Umpire" },
      ],
    },
    {
      name: "Business",
      streams: [
        {
          name: "Start-UP",
          subStreams: [
            { name: "Finance" },
            { name: "Idea Development" },
            { name: "Company Registerations" },
            { name: "Franchising" },
            { name: "marketing" },
            { name: "HRM" },
          ],
        },
      ],
    },
    {
      name: "Graduation in Sciences",
      streams: [
        {
          name: "Engineering Sciences",
          subStreams: [
            { name: "Aeronautical" },
            { name: "Agriculture" },
            { name: "Artifical Intelligence" },
            { name: "Aerospace" },
            { name: "Automobile" },
            { name: "Biomedical" },
            { name: "Biotech" },
            { name: "Ceremic" },
            { name: "Chemical" },
            { name: "Civil" },
            { name: "Communication" },
            { name: "CS&IT" },
            { name: "Construction" },
            { name: "Electrical" },
            { name: "ENTC" },
            { name: "Electronics" },
            { name: "Environmental " },
            { name: "Industrial" },
            { name: "Instrumentation" },
            { name: "Marine" },
            { name: "Mechanical" },
            { name: "Mechatronics" },
            { name: "Metallurgy" },
            { name: "Mining" },
            { name: "Petroleum" },
            { name: "Petrochemical" },
            { name: "Power" },
            { name: "Production" },
            { name: "Robotics" },
            { name: "Structural" },
            { name: "Telecommunication" },
            { name: "Textile" },
            { name: "tool" },
            { name: "Transportation" },
          ],
        },
        {
          name: "Medical Srvices",
          subStreams: [
            { name: "MBBS" },
            { name: "BAMS" },
            { name: "BHMS" },
            { name: "BPT" },
            { name: "B.USC" },
            { name: "BUMS" },
            { name: "BSMS" },
            { name: "BNYS" },
            { name: "BDS" },
            { name: "B.pharma" },
            { name: "BOT" },
            { name: "BMLT" },
          ],
        },
        {
          name: "Management Services",
          subStreams: [
            { name: "HRM" },
            { name: "marketing" },
            { name: "Sales and operations" },
            { name: "Aviation" },
            { name: "Logistics and supply chain" },
            { name: "Energy" },
            { name: "Hospital" },
            { name: "Product" },
            { name: "Family Business administration" },
            { name: "NGO" },
            { name: "Import Export" },
            { name: "Foreign Trade" },
            { name: "BBM" },
            { name: "Hospitility" },
            { name: "Investment banking and stock broking" },
          ],
        },
        {
          name: "BSC",
          subStreams: [
            { name: "Chemistry" },
            { name: "Physics" },
            { name: "Maths" },
            { name: "Zoology" },
            { name: "Botany" },
            { name: "Stats" },
            { name: "Home Sciences" },
            { name: "Agriculture" },
            { name: "Animation" },
            { name: "Aquaculture" },
            { name: "Avaition" },
            { name: "Biochemistry" },
            { name: "CS" },
            { name: "Dietics" },
            { name: "Electronics" },
            { name: "Fashion" },
            { name: "Food" },
            { name: "Forensic Science" },
            { name: "Forestry" },
            { name: "Medical Technology" },
            { name: "Microbiology" },
            { name: "Multimedia" },
            { name: "Nautical Sciences" },
            { name: "Nursing" },
            { name: "Nutrition" },
            { name: "Physiotherapy" },
            { name: "Psychology" },
            { name: "Genitics" },
            { name: "Interior designing" },
            { name: "Horticulture" },
            { name: "Anatomy" },
            { name: "Anthropology" },
          ],
        },
        {
          name: "Armed Forces",
          subStreams: [
            { name: "Army" },
            { name: "Navy" },
            { name: "Airforce" },
          ],
        },
        {
          name: "Design Courses",
          subStreams: [
            { name: "Fashion" },
            { name: "Graphics" },
            { name: "Interior designing" },
            { name: "Animation" },
            { name: "Industry" },
            { name: "Jwellery" },
            { name: "Textile" },
            { name: "Ceramic" },
            { name: "Product" },
          ],
        },
        { name: "Merchant navy" },
        { name: "Architecture" },
        { name: "BCA" },
        { name: "Acturial Sciences" },
        { name: "Technical Writers" },
        { name: "Astronomy" },
      ],
    },
    {
      name: "Graduation in Arts",
      streams: [
        { name: "B.com" },
        { name: "LLB" },
        { name: "CMA" },
        { name: "CA" },
        { name: "BBA" },
        { name: "CS" },
        { name: "CFP" },
        { name: "B.Economics" },
        {
          name: "Journaliam and mass media",
          subStreams: [{ name: "BJMC" }, { name: "BJ" }, { name: "BMC" }],
        },
        { name: "Investment Banking" },
        { name: "Stock Broking and Insurance" },
      ],
    },
    {
      name: "Graduation in Arts",
      streams: [
        {
          name: "BA",
          subStreams: [
            { name: "Any Speaking Language" },
            { name: "Any Speaking Language Hons" },
            { name: "Computer Applications" },
            { name: "BA LLB HONS" },
            { name: "Economics Hons" },
            { name: "Educations" },
            { name: "Educations Hons" },
            { name: "Literature" },
            { name: "Literature HONS" },
            { name: "Fine Arts" },
            { name: "Political Sciences Hons" },
            { name: "Geography" },
            { name: "Home Sciences" },
            { name: "Journalism" },
            { name: "Criminalogy" },
            { name: "Mathematics" },
            { name: "Music" },
            { name: "Philosophy Hons" },
            { name: "Physical Education" },
            { name: "Psychology Hons" },
            { name: "Socialogy Hons" },
            { name: "Statistics" },
            { name: "Beautician" },
          ],
        },
        {
          name: "Civil Services",
          subStreams: [
            { name: "All Government exams" },
            { name: "Railway Exams" },
            { name: "SSC" },
            { name: "Banks" },
            { name: "Teachers" },
          ],
        },
      ],
    },
    {
      name: "Post Graduation",
      streams: [
        { name: "M.Arch" },
        { name: "M.A" },
        { name: "MBA" },
        { name: "MCA" },
        { name: "M.com" },
        { name: "M.ed" },
        { name: "LLM" },
        { name: "M.phil" },
        { name: "M.Sc" },
        { name: "M.Tech" },
        { name: "PGDM" },
        { name: "PG Medical (MD/MS/DM/Mch" },
        { name: "MDS" },
        { name: "Doctor of Philosophy (Ph.D)" },
      ],
    },
    {
      name: "Post Graduation (Foreign Education)",
      streams: [{ name: "Sciences" }, { name: "Commerce" }, { name: "Arts" }],
    },
    {
      name: "Entrance Exams",
      streams: [
        { name: "JEE Mains" },
        { name: "JEE Advance" },
        { name: "VITEEE" },
        { name: "COMED-K" },
        { name: "AIIMS" },
        { name: "NEET" },
        { name: "CMC- VELLORE" },
        { name: "JIPMER" },
        { name: "BITSAT" },
        { name: "CLAT" },
        { name: "AIEEE" },
        { name: "IIST" },
        { name: "IISc" },
        { name: "CET" },
        { name: "NDA" },
        { name: "NEST" },
        { name: "NATA" },
      ],
    },
    {
      name: "Talent Tests",
      streams: [
        { name: "NTSE" },
        { name: "KVPY" },
        { name: "HBBVS" },
        { name: "NSO" },
        { name: "NCO" },
        { name: "UCO" },
        { name: "MTSE" },
        { name: "IMO" },
        { name: "IOS" },
        { name: "RMO" },
        { name: "IOEL" },
      ],
    },
  ],
};
